package UserInterface;

import Business.SystemAdmin.Person;
import Business.SystemAdmin.UserAccount;
import UserInterface.Supplier.SupplierWorkAreaJPanel;
import UserInterface.Marketing.MarketingWorkAreaJPanel;
import UserInterface.SystemAdmin.SystemAdminWorkAreaJPanel;
import UserInterface.Customer.CustomerWorkAreaJPanel;
import UserInterface.Util.*;
import Business.*;
import Business.Customer.Customer;
import Business.ProductManagement.Supplier;
import UserInterface.ManagementReport.ManagementReport;
import javax.swing.JOptionPane;


/**
 *
 * @author peera
 */
public class LoginJPanel extends javax.swing.JPanel {

    private Business business;

    public LoginJPanel(Business b) 
    {
        initComponents();
        business = b;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Login");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jLabel2.setText("Username:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel3.setText("Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        UsernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsernameTextFieldKeyTyped(evt);
            }
        });

        add(UsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 100, -1));

        PasswordTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordTextFieldKeyTyped(evt);
            }
        });

        add(PasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 100, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

    }// </editor-fold>//GEN-END:initComponents

    private void PasswordTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTextFieldKeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldKeyTyped

    private void UsernameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameTextFieldKeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: CANCEL BUTTON
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here: LOGIN BUTTON
        
        char[] password = PasswordTextField.getPassword();
        String passwordString = new String(password);
        Supplier supplier ;
        Customer customer;
        UserAccount userAccount = business.getUserAccountDirectory().authenticateUser(UsernameTextField.getText(), passwordString);
        
        if (userAccount != null)
        {                 
            Person p = userAccount.getPerson();
            
            if (p.getRole() == Person.Role.CUSTOMER)
            { 
                customer = business.getCustomerDirectory().getCustomerFromPerson(p);
                CustomerWorkAreaJPanel cwajp = new CustomerWorkAreaJPanel(business, userAccount,customer);
                CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("CustomerWorkAreaJPanel", cwajp);                    
            }               
            else if (p.getRole() == Person.Role.SUPPLIER)
            {   
                supplier = business.getSupplierDirectory().getSupplierFromPerson(p);
                SupplierWorkAreaJPanel pmwajp = new SupplierWorkAreaJPanel(supplier);
                CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("SupplierWorkAreaJPanel", pmwajp);                    
            }    
            else if (p.getRole() == Person.Role.MARKETING)
            {
                MarketingWorkAreaJPanel mwajp = new MarketingWorkAreaJPanel(business);
                CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("MarketingWorkAreaJPanel", mwajp);                    
            }
           else if (p.getRole() == Person.Role.SYSTEM_ADMIN)
            {
                SystemAdminWorkAreaJPanel sawajp = new SystemAdminWorkAreaJPanel(business);
                CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("SystemAdminWorkAreaJPanel", sawajp);                  
            }   
           else if(p.getRole() == Person.Role.REPORT)
           {
               ManagementReport sawajp = new ManagementReport(business);
               CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ManagementReport", sawajp);
           }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Incorrect username or password");  
            UsernameTextField.setText("");
            PasswordTextField.setText("");
        }             
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    
}
