package UserInterface.Supplier;

import Business.ProductManagement.Product;
import Business.ProductManagement.ProductDirectory;
import UserInterface.Util.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SearchProductJPanel extends javax.swing.JPanel {
    
    private ProductDirectory productdirectory;
    private ArrayList <Product> productlist;
    public SearchProductJPanel(ProductDirectory p) 
    {
        initComponents();
        productdirectory = p;
    }
    public void refresh()
    {
       int rowCount = productTable.getRowCount();
      int i;
      for(i = rowCount-1;i>=0;i--)
      {
         ((DefaultTableModel)productTable.getModel()).removeRow(i);
        
      }
    if(productlist.size() != 0)
    {
        for(Product p: productlist)
      {
          Object[] product_row = new Object[3];
          product_row[0] = p;
          product_row[1] = p.getPrice();
          product_row[2] = p.getAvail();   
          ((DefaultTableModel) productTable.getModel()).addRow(product_row);
      }
    }
    else
    {
             JOptionPane.showMessageDialog(this, "No matching product!");  
    }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        ResultLabel = new javax.swing.JLabel();
        SearchComboBox = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Search Product");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel2.setText("Search by:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });
        add(SearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 170, -1));

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 640, 200));

        ResultLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        add(ResultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 340, 20));

        SearchComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "ID", "Price", "Description" }));
        add(SearchComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: BACK
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
// TODO add your handling code here:
        String item = SearchTextField.getText();
        if(((String)SearchComboBox.getSelectedItem()).equals("Name"))
        {
            productlist = productdirectory.searchProductByName(item);
            refresh();
        }
        if(((String)SearchComboBox.getSelectedItem()).equals("ID"))
        {
            productlist = productdirectory.searchProductById(item);
            refresh();
        }
        if(((String)SearchComboBox.getSelectedItem()).equals("Price"))
        {
            productlist = productdirectory.searchProductByPrice(item);
            refresh();
        }
        if(((String)SearchComboBox.getSelectedItem()).equals("Description"))
        {
            productlist = productdirectory.searchProductByDescription(item);
            refresh();
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JComboBox SearchComboBox;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
    
}
