package UserInterface.Supplier;

import Business.ProductManagement.Product;
import Business.ProductManagement.ProductDirectory;
import UserInterface.Util.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

public class ViewProductDetailJPanel extends javax.swing.JPanel {
    
     private ProductDirectory productdirectory;
     private Product product;
    public ViewProductDetailJPanel(Product p,ProductDirectory q) 
    {
        initComponents();
        productdirectory = q;
        product = p;
        IDTextField.setText(product.getID());
        NameTextField.setText(product.getName());
        PriceTextField.setText(product.getPrice());
        CategoryTextField.setText(product.getCategory());
        AvailabilityTextField.setText(product.getAvail());
        
         ArrayList <String> desc = product.getFeatures();
        for(String aa:desc)
        {
             ((DefaultListModel)jList1.getModel()).addElement(aa);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NameTextField = new javax.swing.JTextField();
        CategoryTextField = new javax.swing.JTextField();
        PriceTextField = new javax.swing.JTextField();
        AvailabilityTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        updateButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("View Product Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel3.setText("Category:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel4.setText("Price:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel5.setText("Availability:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel6.setText("Features:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        NameTextField.setBackground(new java.awt.Color(204, 204, 204));
        NameTextField.setEditable(false);
        add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 180, -1));

        CategoryTextField.setBackground(new java.awt.Color(204, 204, 204));
        CategoryTextField.setEditable(false);
        add(CategoryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 180, -1));

        PriceTextField.setBackground(new java.awt.Color(204, 204, 204));
        PriceTextField.setEditable(false);
        add(PriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 120, -1));

        AvailabilityTextField.setBackground(new java.awt.Color(204, 204, 204));
        AvailabilityTextField.setEditable(false);
        add(AvailabilityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 120, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel7.setText("ID:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        IDTextField.setBackground(new java.awt.Color(204, 204, 204));
        IDTextField.setEditable(false);
        add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 120, -1));

        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 290, -1));

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
// TODO add your handling code here:
        
        UpdateProductJPanel vcdjp = new UpdateProductJPanel(product);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("UpdateProductJPanel", vcdjp);        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: CANCEL
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
// TODO add your handling code here: ADD PRODUCT
         productdirectory.removeProduct(product);
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);        
    }//GEN-LAST:event_removeButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AvailabilityTextField;
    private javax.swing.JTextField CategoryTextField;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    
}
