package UserInterface.Marketing;

import Business.Business;
import Business.Customer.CustomerDirectory;
import Business.Market.Market;
import Business.Market.MarketList;
import UserInterface.Util.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ManageMarketJPanel extends javax.swing.JPanel {
    
    private Business business;
    private  MarketList marketlist;
    private  CustomerDirectory customerdirectory;
    private Market selectmarket;
    public ManageMarketJPanel(Business a) 
    {
        initComponents();     

        business = a;
        marketlist = business.getMarketList();
        customerdirectory = business.getCustomerDirectory();
        refresh();
    }
     private void refresh()
    {
        int rowCount = marketTable.getRowCount();
        int i;
        for (i = rowCount-1; i >= 0; i--)
        {
            ((DefaultTableModel)marketTable.getModel()).removeRow(i);
        }
        
        ArrayList <Market> markets = business.getMarketList().getMarketList();
        
        for (Market p : markets)
        {            
            Object[] market_row = new Object[2];
            
            market_row[0] = p;
            market_row[1] = p.getIncome();           
        ((DefaultTableModel)marketTable.getModel()).addRow(market_row);
        }
    }        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        marketTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Manage Markets");
        add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 210, 40));

        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, -1, -1));

        marketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Market Name", "Income"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        marketTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                marketTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(marketTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 720, 350));

        jButton1.setText("Add Market");
        jButton1.setToolTipText("Create Business");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 120, -1));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jButton7.setText("View Detail");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
         int rr = marketTable.getSelectionModel().getLeadSelectionIndex();
        if(rr < 0 || rr >= marketTable.getRowCount())
       {
             return ;
       }
        else
        {
            
        ViewMarketJPanel amjp = new ViewMarketJPanel(selectmarket,business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ViewMarketJPanel", amjp);    
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here: REFRESH
        refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here: ADD
 
        AddMarketJPanel amjp = new AddMarketJPanel(business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("AddMarketJPanel", amjp);          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
// TODO add your handling code here: BACK BUTTON
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton12ActionPerformed

private void marketTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marketTableMousePressed
// TODO add your handling code here:
        int rr = marketTable.getSelectionModel().getLeadSelectionIndex();
        if(rr < 0 || rr >= marketTable.getRowCount())
       {
             return ;
       }

  selectmarket = (Market)marketTable.getValueAt(rr,0);
}//GEN-LAST:event_marketTableMousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable marketTable;
    // End of variables declaration//GEN-END:variables
    
}
