package UserInterface.Marketing;

import Business.Business;
import Business.Market.Solution;
import Business.Market.SolutionDirectory;
import UserInterface.Util.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ManageSolutionJPanel extends javax.swing.JPanel {

    private Business business;
    private SolutionDirectory solutiondirectory;
    private Solution selectsolution;
    public ManageSolutionJPanel(Business a) 
    {
        initComponents();  
        business = a;
        solutiondirectory = business.getSolutionDirectory();
        refresh();
    }
        
     private void refresh()
    {
        int rowCount = solutionTable.getRowCount();
        int i;
        for (i = rowCount-1; i >= 0; i--)
        {
            ((DefaultTableModel)solutionTable.getModel()).removeRow(i);
        }
        
        ArrayList <Solution> solutions = business.getSolutionDirectory().getSolutionList();
        
        for (Solution p : solutions)
        {            
            Object[] solution_row = new Object[2];
            solution_row[0] = p;
            solution_row[1] = p.getName();  
 
        ((DefaultTableModel)solutionTable.getModel()).addRow(solution_row);
        }
    }        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        solutionTable = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Manage Solutions");
        add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 240, 40));

        solutionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Solution ID", "Solution Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        solutionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                solutionTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(solutionTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 700, 350));

        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, -1, -1));

        jButton1.setText("View Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 110, -1));

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        
        AddNewSolutionJPanel ansjp = new AddNewSolutionJPanel(business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("AddSolutionJPanel", ansjp);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here: // VIEW PRODUCT
        int rr = solutionTable.getSelectionModel().getLeadSelectionIndex();
        if(rr < 0 || rr >= solutionTable.getRowCount())
       {
             return ;
       }   
        else
        {
            System.out.println(selectsolution);
        ViewSolutionDetailJPanel vcdjp = new ViewSolutionDetailJPanel(selectsolution,business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ViewSolutionDetailJPanel", vcdjp);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
// TODO add your handling code here: BACK BUTTON
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton12ActionPerformed

private void solutionTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solutionTableMousePressed
// TODO add your handling code here:
        int rr = solutionTable.getSelectionModel().getLeadSelectionIndex();
        if(rr < 0 || rr >= solutionTable.getRowCount())
       {
             return ;
       }

  selectsolution = (Solution)solutionTable.getValueAt(rr,0);
}//GEN-LAST:event_solutionTableMousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable solutionTable;
    // End of variables declaration//GEN-END:variables
    
}
