package UserInterface.Marketing;

import Business.Business;
import UserInterface.Util.*;

public class MarketingWorkAreaJPanel extends javax.swing.JPanel {

    private Business business;
    public MarketingWorkAreaJPanel(Business a) 
    {
        initComponents();
        business = a;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        TitleLabel = new javax.swing.JLabel();
        SolutionButton = new javax.swing.JButton();
        MarketButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Marketing Staff Work Area");
        add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 500, 40));

        SolutionButton.setText("Manage Solutions");
        SolutionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolutionButtonActionPerformed(evt);
            }
        });

        add(SolutionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 190, -1));

        MarketButton.setText("Manage Markets");
        MarketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarketButtonActionPerformed(evt);
            }
        });

        add(MarketButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, -1));

    }// </editor-fold>//GEN-END:initComponents

    private void MarketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarketButtonActionPerformed
// TODO add your handling code here:

        ManageMarketJPanel ancjp = new ManageMarketJPanel(business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ManageMarketJPanel", ancjp);             
    }//GEN-LAST:event_MarketButtonActionPerformed

    private void SolutionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolutionButtonActionPerformed
// TODO add your handling code here:

        ManageSolutionJPanel ancjp = new ManageSolutionJPanel(business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ManageSolutionJPanel", ancjp);         
    }//GEN-LAST:event_SolutionButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MarketButton;
    private javax.swing.JButton SolutionButton;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
    
}
