package UserInterface.Marketing;

import Business.Business;
import Business.Market.Market;
import Business.Market.Solution;
import Business.ProductManagement.Product;
import UserInterface.Util.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

public class ViewSolutionDetailJPanel extends javax.swing.JPanel {
    
   private Business business;
   private Solution solution;
   private HashMap <Product,Integer> products ;
   private HashMap <Market,Double> targetmarket ;
   private ArrayList <String> benefit;
    public ViewSolutionDetailJPanel(Solution p,Business q) 
    {
        initComponents();
        business = q;
        solution = p;
        products = p.getProductList();
        targetmarket = p.getTargetMarket();
        benefit = p.getBenefit();
        IDTextField.setText(solution.getID());
        NameTextField.setText(solution.getName());
        
        int rowCount = productlist.getRowCount();
        int i;
        for (i = rowCount-1; i >= 0; i--)
        {
            ((DefaultTableModel)productlist.getModel()).removeRow(i);
        }
        Iterator it = products.entrySet().iterator();
        while(it.hasNext())
        {      
             Map.Entry entry   = (Map.Entry)it.next()   ;    
            Object[] product_row = new Object[3];       
            product_row[0] = entry.getKey();
            product_row[1] = entry.getValue();            
           ((DefaultTableModel)productlist.getModel()).addRow(product_row);
        }
        
        
        
        rowCount = targetMarketTable.getRowCount();
        for (i = rowCount-1; i >= 0; i--)
        {
            ((DefaultTableModel)targetMarketTable.getModel()).removeRow(i);
        }
       it = targetmarket.entrySet().iterator();
        while(it.hasNext())
        {      
             Map.Entry entry   = (Map.Entry)it.next()   ;    
            Object[] product_row = new Object[3];       
            product_row[0] = entry.getKey();
            product_row[1] = entry.getValue();            
           ((DefaultTableModel)targetMarketTable.getModel()).addRow(product_row);
        }

        for(String aa:benefit)
        {
             ((DefaultListModel)jList1.getModel()).addElement(aa);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productlist = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        targetMarketTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("View Solution");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel2.setText("Solution Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, -1, -1));

        NameTextField.setBackground(new java.awt.Color(204, 204, 204));
        NameTextField.setEditable(false);
        add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 180, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel7.setText("Solution ID:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        IDTextField.setBackground(new java.awt.Color(204, 204, 204));
        IDTextField.setEditable(false);
        add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 90, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel8.setText("Product List:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 20));

        productlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productlist);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 310, 120));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 750, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 750, 10));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel9.setText("Target Market:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, 20));

        targetMarketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Market", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(targetMarketTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 340, 120));

        jList1.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jList1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 310, 120));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel10.setText("Benefit:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 20));

        jButton11.setText("Remove");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
// TODO add your handling code here:
        business.getSolutionDirectory().removeSolution(solution);
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:    
        
        UpdateSolutionJPanel usjp = new UpdateSolutionJPanel(solution,business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("UpdateSolutionJPanel", usjp);        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable productlist;
    private javax.swing.JTable targetMarketTable;
    // End of variables declaration//GEN-END:variables
    
}
