package UserInterface.Customer;

import Business.Customer.Customer;
import Business.Customer.Order;
import UserInterface.Util.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class CheckOrderStatusJPanel extends javax.swing.JPanel {

   Customer customer;
   Order selectorder;
    public CheckOrderStatusJPanel(Customer p) 
    {
        initComponents();
        customer = p;
        refresh();
    }    
    
    public void refresh()
  {
      int rowCount = ordertable.getRowCount();
      int i;
      for(i = rowCount-1;i>=0;i--)
      {
         ((DefaultTableModel)ordertable.getModel()).removeRow(i);
        
      }
        ArrayList<Order> orders = customer.getOrders();
       for(Order p: orders)
      {  
          if(p.getStatus())
          {
          Object[] orders_row = new Object[4];
          orders_row[0] = p;
          orders_row[1] = p.getOrderDate();
          orders_row[2] = p.getTotalPrice();
          orders_row[3] = p.getStatus();
          
          ((DefaultTableModel) ordertable.getModel()).addRow(orders_row);
          }
      }
  }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        viewButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        cancelorderButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Check Order Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Order Date", "TotalPrice", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ordertableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(ordertable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 550, 270));

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        cancelorderButton.setText("Cancel Order");
        cancelorderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelorderButtonActionPerformed(evt);
            }
        });
        add(cancelorderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here: REFRESH  
        refresh();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cancelorderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelorderButtonActionPerformed
// TODO add your handling code here: CANCEL ORDER
                    customer.removeOrder(selectorder);
             CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);          
}//GEN-LAST:event_cancelorderButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
// TODO add your handling code here: VIEW ORDER
     int rr = ordertable.getSelectionModel().getLeadSelectionIndex();
     if(rr < 0 || rr >= ordertable.getRowCount())
     {
         return ;
     }
     {
        ViewOrderDetailJPanel vodjp = new ViewOrderDetailJPanel(selectorder,customer);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ViewOrderDetailJPanel", vodjp);   
     }
}//GEN-LAST:event_viewButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
// TODO add your handling code here: BACK
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);                
}//GEN-LAST:event_backButtonActionPerformed

private void ordertableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordertableMousePressed
// TODO add your handling code here:
    
        int rr = ordertable.getSelectionModel().getLeadSelectionIndex();
     if(rr < 0 || rr >= ordertable.getRowCount())
     {
         return ;
     }

  selectorder = (Order)ordertable.getValueAt(rr,0);
}//GEN-LAST:event_ordertableMousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelorderButton;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ordertable;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
    
}
