package UserInterface.Customer;

import Business.SystemAdmin.UserAccount;
import UserInterface.Util.*;
import javax.swing.JOptionPane;

public class ManageAccountJPanel extends javax.swing.JPanel {
    
    private UserAccount useraccount;
    public ManageAccountJPanel(UserAccount a) 
    {
        initComponents();
        useraccount = a;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PasswordField2 = new javax.swing.JPasswordField();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Manage Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 3, 14));
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Change Password");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 160, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel16.setText("New Password:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel17.setText("Verify Password:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));
        add(PasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 160, -1));
        add(ConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 160, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel18.setText("Current Password:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));
        add(PasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 160, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 730, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: CANCEL
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
// TODO add your handling code here: CREATE
        char[] password1 = PasswordField1.getPassword();
        String passwordString = new String(password1);      
        if(!passwordString.equals(useraccount.getPassword()))
        {
             JOptionPane.showMessageDialog(this, "Incorrect  password"); 
        }
        password1 = PasswordField2.getPassword();
       passwordString = new String(password1);  
       
        char[] password2 = ConfirmPasswordField.getPassword();
        String passwordString2 = new String(password2); 
        if(passwordString.equals(passwordString2))
        {
             useraccount.setPassword(passwordString);
        }
        else
        {
              JOptionPane.showMessageDialog(this, "new password isn't equal to vertify password"); 
        }
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
}//GEN-LAST:event_saveButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JPasswordField PasswordField2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
    
}
