package UserInterface.Customer;


import Business.Customer.OrderItem;
import UserInterface.Util.*;

public class ViewOrderItemDetailJPanel extends javax.swing.JPanel {
    
    private OrderItem orderItem;
    public ViewOrderItemDetailJPanel(OrderItem a) 
    {
        initComponents();    
        orderItem = a;
        
        nameTextField.setText(orderItem.getProduct().toString());
         price.setText(Double.toString(orderItem.getPaidPrice()));
        quantity.setText(Integer.toString(orderItem.getQuantity()));
        categoryTextField.setText(orderItem.getProduct().getCategory());
        supplier.setText(orderItem.getSupplier().getPerson().toString());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        categoryTextField = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        supplier = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("View Order Item Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel2.setText("Product Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel3.setText("Category:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel4.setText("Price:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel5.setText("Quantity:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        nameTextField.setBackground(new java.awt.Color(204, 204, 204));
        nameTextField.setEditable(false);
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, -1));

        price.setBackground(new java.awt.Color(204, 204, 204));
        price.setEditable(false);
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 180, -1));

        categoryTextField.setBackground(new java.awt.Color(204, 204, 204));
        categoryTextField.setEditable(false);
        add(categoryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, -1));

        quantity.setBackground(new java.awt.Color(204, 204, 204));
        quantity.setEditable(false);
        add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel6.setText("Supplier:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        supplier.setBackground(new java.awt.Color(204, 204, 204));
        supplier.setEditable(false);
        add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: BACK BUTTON
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField supplier;
    // End of variables declaration//GEN-END:variables
    
}
