package UserInterface.Customer;

import Business.Customer.Customer;
import Business.Customer.Order;
import Business.Customer.OrderItem;
import UserInterface.Util.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ViewOrderDetailJPanel extends javax.swing.JPanel {
    
private OrderItem selectorderitem;
private Order order;
private Customer customer;
    public ViewOrderDetailJPanel(Order p,Customer q) 
    {
        initComponents();     
        order = p;
        customer = q;
         orderid.setText(Integer.toString(order.getOrderId()));
         orderdate.setText(order.getOrderDate()+"");
         TotalPriceField.setText(Double.toString(order.getTotalPrice()));
         statusField.setText(order.getStatus()+"");
         refresh();
    }        
    public void refresh()
    {
      int rowCount = orderitemTable.getRowCount();
      int i;
      for(i = rowCount-1;i>=0;i--)
      {
         ((DefaultTableModel)orderitemTable.getModel()).removeRow(i);
        
      }
        ArrayList<OrderItem> orders = order.getOrderItem();
       for(OrderItem p: orders)
      {  
 
          Object[] orders_row = new Object[4];
          orders_row[0] = p;
          orders_row[1] = p.getPaidPrice();
          orders_row[2] = p.getQuantity();
          orders_row[3] = p.getTotalAmount();
          
          ((DefaultTableModel) orderitemTable.getModel()).addRow(orders_row);

      }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderitemTable = new javax.swing.JTable();
        CancelButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        orderid = new javax.swing.JTextField();
        TotalPriceField = new javax.swing.JTextField();
        orderdate = new javax.swing.JTextField();
        statusField = new javax.swing.JTextField();
        viewButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Order Status Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 250, 30));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel2.setText("Order ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel3.setText("Total Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel4.setText("Status:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        jLabel5.setText("Order Items");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        orderitemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderitemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderitemTableMousePressed(evt);
            }
        });
        orderitemTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                orderitemTableComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(orderitemTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 630, 170));

        CancelButton.setText("Cancel Order");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel8.setText("Order Date:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        orderid.setBackground(new java.awt.Color(204, 204, 204));
        orderid.setEditable(false);
        add(orderid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, -1));

        TotalPriceField.setBackground(new java.awt.Color(204, 204, 204));
        TotalPriceField.setEditable(false);
        add(TotalPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, -1));

        orderdate.setBackground(new java.awt.Color(204, 204, 204));
        orderdate.setEditable(false);
        add(orderdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 120, -1));

        statusField.setBackground(new java.awt.Color(204, 204, 204));
        statusField.setEditable(false);
        add(statusField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 120, -1));

        viewButton.setText("View Item");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
// TODO add your handling code here:
        
        ViewOrderItemDetailJPanel voidjp = new ViewOrderItemDetailJPanel(selectorderitem);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ViewOrderItemDetailJPanel", voidjp);        
    }//GEN-LAST:event_viewButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
// TODO add your handling code here: CANCEL ORDER       
        customer.removeOrder(order);
       CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: BACK
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton2ActionPerformed

private void orderitemTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderitemTableMousePressed
// TODO add your handling code here:
         int rr = orderitemTable.getSelectionModel().getLeadSelectionIndex();
     if(rr < 0 || rr >= orderitemTable.getRowCount())
     {
         return ;
     }

  selectorderitem = (OrderItem)orderitemTable.getValueAt(rr,0);
}//GEN-LAST:event_orderitemTableMousePressed

private void orderitemTableComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_orderitemTableComponentHidden
// TODO add your handling code here:
}//GEN-LAST:event_orderitemTableComponentHidden
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField TotalPriceField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField orderdate;
    private javax.swing.JTextField orderid;
    private javax.swing.JTable orderitemTable;
    private javax.swing.JTextField statusField;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
    
}
