package UserInterface.Customer;


import Business.Customer.Customer;
import Business.Customer.MasterOrderCatalog;
import Business.Customer.Order;
import Business.Customer.OrderItem;
import Business.ProductManagement.Product;
import Business.ProductManagement.Supplier;
import UserInterface.Util.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;

public class ViewProductDetailJPanel extends javax.swing.JPanel {
    
    private Product product;
    private MasterOrderCatalog masterordercatalog;
    private Order order;
    private Customer customer;
    private OrderItem orderItem;
    private Supplier selectedsupplier;
     public ViewProductDetailJPanel() 
     {
         
     }
    public ViewProductDetailJPanel(Product p,Order q,MasterOrderCatalog c,Customer d,Supplier s) 
    {
        initComponents();     
        product = p;
        masterordercatalog = c;
        order = q;
        customer = d;
        selectedsupplier =s;
        
        nameField.setText(product.getName());
        priceField.setText(product.getPrice());
        availabilityField.setText(product.getAvail());
        category.setText(product.getCategory());
        
        ArrayList <String> desc = product.getFeatures();
        for(String aa:desc)
        {
             ((DefaultListModel)jList1.getModel()).addElement(aa);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addtocartButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        availabilityField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        quantity = new javax.swing.JSpinner();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("View Product Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        addtocartButton.setText("Add to Cart");
        addtocartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartButtonActionPerformed(evt);
            }
        });
        add(addtocartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel2.setText("Product Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel3.setText("Category:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel4.setText("Price:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel5.setText("Availability:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel7.setText("Features:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel6.setText("Quantity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        nameField.setBackground(new java.awt.Color(204, 204, 204));
        nameField.setEditable(false);
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, -1));

        priceField.setBackground(new java.awt.Color(204, 204, 204));
        priceField.setEditable(false);
        add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 180, -1));

        category.setBackground(new java.awt.Color(204, 204, 204));
        category.setEditable(false);
        add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 180, -1));

        availabilityField.setBackground(new java.awt.Color(204, 204, 204));
        availabilityField.setEditable(false);
        add(availabilityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, -1));

        jList1.setBackground(new java.awt.Color(204, 204, 204));
        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 290, 130));
        add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: BACK BUTTON
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addtocartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartButtonActionPerformed
// TODO add your handling code here: ADD TO CART BUTTON     
    if(order == null)
   {
    order = masterordercatalog.newOrder();
    customer.newOrder(order);
    order.setCustomer(customer);
   SimpleDateFormat bartDateFormat = new SimpleDateFormat("MM/dd/yyyy");

    Date date = new Date();
    order.setOrderDate(date);
    order.setOrderId();
   }

    boolean mark = true;
    OrderItem temp = null;
    ArrayList <OrderItem> items = order.getOrderItem();
    for(OrderItem p:items)
    {
       if(product.getID().equals(p.getProduct().getID()))
       {
           mark = false;
           temp = p;
           break;
       }
           
    }
   if(mark)
   {
    orderItem = order.newOrderItem();
    orderItem.setPaidPrice(Double.parseDouble(product.getPrice()));
    orderItem.setProduct(product);
    orderItem.setQuantity((Integer)(quantity.getValue()));
    orderItem.setSupplier(selectedsupplier);
    orderItem.setTotalAmount(orderItem.getPaidPrice()*(new Integer(orderItem.getQuantity())).doubleValue());

   }
   else
   {
        temp.setQuantity((Integer)(quantity.getValue())+temp.getQuantity());
        temp.setTotalAmount(temp.getPaidPrice()*temp.getQuantity());

   }
         CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);    
}//GEN-LAST:event_addtocartButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtocartButton;
    private javax.swing.JTextField availabilityField;
    private javax.swing.JTextField category;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JSpinner quantity;
    // End of variables declaration//GEN-END:variables
    
}
