package UserInterface.SystemAdmin;

import Business.SystemAdmin.Person;
import Business.SystemAdmin.UserAccount;
import UserInterface.Util.*;
import Business.Business;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author peera
 */
public class AddUserAccountJPanel extends javax.swing.JPanel {
    
    private Business business;
    
    /**
     * Creates new form NewUserAccountJPanel
     */
    public AddUserAccountJPanel(Business b) 
    {
        initComponents();
        
        business = b;        
        
        for (Person.Role role : Person.Role.values())
        {
            roleComboBox.addItem(role);
        }
        
        displayPersonByRole(Person.Role.CUSTOMER);
    }
    
    private void displayPersonByRole(Person.Role role)
    {
        ArrayList<Person> personList = business.getPersonDirectory().getPersonsByRole(role);
        personComboBox.removeAllItems();
        for (Person p : personList)
        {
            personComboBox.addItem(p);
        }        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        personComboBox = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Create User Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel15.setText("Username:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));
        add(UserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 160, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel16.setText("Password:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel17.setText("Confirm Password:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));
        add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 160, -1));
        add(ConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 160, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel18.setText("Role:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        roleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBoxActionPerformed(evt);
            }
        });
        add(roleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 170, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel19.setText("Select Person:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        personComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personComboBoxActionPerformed(evt);
            }
        });
        add(personComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
// TODO add your handling code here:
        
        displayPersonByRole((Person.Role)roleComboBox.getSelectedItem());
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: CANCEL
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here: CREATE
        
        // Create User Account
        char[] password = PasswordField.getPassword();
        String passwordString = new String(password);        
        char[] confirmPwd = ConfirmPasswordField.getPassword();
        String confirmString = new String(confirmPwd);        
        
        // compare password and confirm password
        if (!passwordString.equals(confirmString))
        {
            JOptionPane.showMessageDialog(this, "Please check password again");
            
            return;
        }        
        
        if (business.getUserAccountDirectory().isUserNameUsed(UserNameTextField.getText()))
        {
            JOptionPane.showMessageDialog(this, "This username is already used");
            
            return;            
        }
        
        if ((Person)personComboBox.getSelectedItem() != null)
        {
            UserAccount ua = business.getUserAccountDirectory().newUserAccount();
            ua.setUserName(UserNameTextField.getText());
            ua.setPassword(passwordString);
            ua.setPerson((Person)personComboBox.getSelectedItem());
            
            JOptionPane.showMessageDialog(this, "User account created successfully!");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select the person");
            return;
        }
        
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton1ActionPerformed

private void personComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_personComboBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JComboBox personComboBox;
    private javax.swing.JComboBox roleComboBox;
    // End of variables declaration//GEN-END:variables
    
}
