/*
 * ManagePersonJPanel.java
 *
 * Created on January 27, 2008, 12:44 AM
 */

package UserInterface.SystemAdmin;

import Business.Business;
import Business.SystemAdmin.Person;
import Business.SystemAdmin.UserAccount;
import UserInterface.Util.*;
import java.util.ArrayList;
import javax.swing.table.*;

public class ManagePersonJPanel extends javax.swing.JPanel {
    
    private Business business;
    private Person selectperson;
    /**
     * Creates new form ManagePersonJPanel
     */
    public ManagePersonJPanel(Business b) 
    {
        initComponents();
        
        business = b;        
        
        refresh();        
    }
    
    private void refresh()
    {
        int rowCount = personTable.getRowCount();
        int i;
        for (i = rowCount-1; i >= 0; i--)
        {
            ((DefaultTableModel)personTable.getModel()).removeRow(i);
        }
        
        ArrayList<Person> personList = business.getPersonDirectory().getPersonList();
        
        for (Person p : personList)
        {            
            Object[] user_row = new Object[4];
            
            user_row[0] = p;
            user_row[1] = p.getRole();            
            user_row[2] = p.getPhoneNumber();
            user_row[3] = p.getEmail();
            
            ((DefaultTableModel)personTable.getModel()).addRow(user_row);
        }
    }        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Manage Persons");
        add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 230, 40));

        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person Name", "Role", "Phone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                personTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(personTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 770, 320));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, -1, -1));

        jButton1.setText("Add Person");
        jButton1.setToolTipText("Create User Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 110, -1));

        jButton5.setText("View Detail");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here: VIEW DETAILS
        int rr = personTable.getSelectionModel().getLeadSelectionIndex();
        if(rr < 0 || rr >= personTable.getRowCount())
        {
             return ;
         }
        else
        {
        ViewPersonDetailJPanel vuadjp = new ViewPersonDetailJPanel(selectperson);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ViewUserAccountDetailJPanel", vuadjp);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here: ADD
        
        AddPersonJPanel nuajp = new AddPersonJPanel(business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("AddPersonJPanel", nuajp);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here: REFRESH
        refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
// TODO add your handling code here: BACK BUTTON
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton12ActionPerformed

private void personTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personTableMousePressed
int rr = personTable.getSelectionModel().getLeadSelectionIndex();
if(rr < 0 || rr >= personTable.getRowCount())
{
    return ;
}

  selectperson = (Person)personTable.getValueAt(rr,0);// TODO add your handling code here:
}//GEN-LAST:event_personTableMousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable personTable;
    // End of variables declaration//GEN-END:variables
    
}
