package UserInterface.SystemAdmin;

import Business.Business;
import Business.ProductManagement.Supplier;
import Business.ProductManagement.SupplierDirectory;
import UserInterface.Util.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ManageSupplierJPanel extends javax.swing.JPanel {
    
    Business business;
    SupplierDirectory supplierdirectory;
    Supplier selectsupplier;
    public ManageSupplierJPanel(Business a) 
    {
        initComponents();     
 
        business = a;
        supplierdirectory = business.getSupplierDirectory();
        refresh();
    }
   
    private void refresh()
    {
        int rowCount = supplierTable.getRowCount();
        int i;
        for (i = rowCount-1; i >= 0; i--)
        {
            ((DefaultTableModel)supplierTable.getModel()).removeRow(i);
        }
        
        ArrayList<Supplier> supplierList = business.getSupplierDirectory().getSupplierList();
        
        for (Supplier p : supplierList)
        {            
            Object[] supplier_row = new Object[3];
            
            supplier_row[0] = p;
            supplier_row[1] = p.getPerson().getPhoneNumber();            
            supplier_row[2] = p.getPerson().getEmail();
   
            
            ((DefaultTableModel)supplierTable.getModel()).addRow(supplier_row);
        }
    }        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Manage Suppliers");
        add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 240, 40));

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supplierTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(supplierTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 810, 350));

        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, -1, -1));

        jButton1.setText("View Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 110, -1));

        jButton2.setText("Add");
        jButton2.setToolTipText("Add Client");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, -1, -1));

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: ADD
        
        AddSupplierJPanel ancjp = new AddSupplierJPanel(business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("AddSupplierJPanel", ancjp);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here: // VIEW CLIENT DETAILS       
        int rr = supplierTable.getSelectionModel().getLeadSelectionIndex();
        if(rr < 0 || rr >= supplierTable.getRowCount())
       {
             return ;
       }
        else
        {
        ViewSupplierDetailJPanel vsdjp = new ViewSupplierDetailJPanel(selectsupplier,business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ViewSupplierDetailJPanel", vsdjp);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
// TODO add your handling code here: BACK BUTTON
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton12ActionPerformed

private void supplierTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMousePressed
        int rr = supplierTable.getSelectionModel().getLeadSelectionIndex();
        if(rr < 0 || rr >= supplierTable.getRowCount())
       {
             return ;
       }

  selectsupplier = (Supplier)supplierTable.getValueAt(rr,0);
    // TODO add your handling code here:
}//GEN-LAST:event_supplierTableMousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable supplierTable;
    // End of variables declaration//GEN-END:variables
    
}
