/*
 * SystemAdminWorkAreaJPanel.java
 *
 * Created on January 26, 2008, 11:51 AM
 */

package UserInterface.SystemAdmin;

import Business.Business;
import UserInterface.SystemAdmin.ManageSupplierJPanel;
import UserInterface.Util.*;

public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private Business business;
    
    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(Business b) 
    {
        initComponents();
        
        business = b;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        TitleLabel = new javax.swing.JLabel();
        userAccountButton = new javax.swing.JButton();
        personButton = new javax.swing.JButton();
        SupplierButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("System Admin Work Area");
        add(TitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 500, 40));

        userAccountButton.setText("Manage User Accounts");
        userAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAccountButtonActionPerformed(evt);
            }
        });

        add(userAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 190, -1));

        personButton.setText("Manage Persons");
        personButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personButtonActionPerformed(evt);
            }
        });

        add(personButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 190, -1));

        SupplierButton.setText("Manage Suppliers");
        SupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierButtonActionPerformed(evt);
            }
        });

        add(SupplierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 190, -1));

    }// </editor-fold>//GEN-END:initComponents

    private void SupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierButtonActionPerformed
// TODO add your handling code here:
        
        ManageSupplierJPanel ancjp = new ManageSupplierJPanel(business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ManageSupplierJPanel", ancjp);
    }//GEN-LAST:event_SupplierButtonActionPerformed

    private void personButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personButtonActionPerformed
// TODO add your handling code here:
        
        ManagePersonJPanel muajp = new ManagePersonJPanel(business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ManagePersonJPanel", muajp);        
    }//GEN-LAST:event_personButtonActionPerformed

    private void userAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAccountButtonActionPerformed
// TODO add your handling code here:

        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(business);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("ManageUserAccountJPanel", muajp);             
    }//GEN-LAST:event_userAccountButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SupplierButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton personButton;
    private javax.swing.JButton userAccountButton;
    // End of variables declaration//GEN-END:variables
    
}
