/*
 * AddPersonJPanel.java
 *
 * Created on January 27, 2008, 5:35 PM
 */

package UserInterface.SystemAdmin;

import Business.SystemAdmin.Person;
import UserInterface.Util.*;

public class UpdatePersonJPanel extends javax.swing.JPanel {
    
    Person person;
    public UpdatePersonJPanel(Person p) 
    {
        initComponents();     
        person = p;
        roleTextField.setText(person.getRole().toString());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stateTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        zipTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        roleTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Update Person");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel2.setText("Last Name*:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 20));

        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 190, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel3.setText("Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 190, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel4.setText("City:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 190, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel5.setText("State:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 40, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel9.setText("Zip Code:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        add(zipTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 50, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel6.setText("Phone:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 160, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 200, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel10.setText("First Name*:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 190, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel11.setText("Birth Date:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, 20));

        add(dobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 80, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("(mm/dd/yyyy)");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel13.setText("Role:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        roleTextField.setBackground(new java.awt.Color(204, 204, 204));
        roleTextField.setEditable(false);
        add(roleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 190, -1));

    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        person.setFirstName(firstNameTextField.getText());
        person.setLastName(lastNameTextField.getText());       
        person.setBirthDate(dobTextField.getText());        
        person.setAddress(addressTextField.getText());
        person.setCity(cityTextField.getText());
        person.setState(stateTextField.getText());
        person.setZip(zipTextField.getText());
        person.setPhoneNumber(phoneTextField.getText());
        person.setEmail(emailTextField.getText());   
       
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField roleTextField;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
    
}
