package UserInterface.SystemAdmin;

import Business.ProductManagement.Supplier;
import UserInterface.Util.*;

public class UpdateSupplierJPanel extends javax.swing.JPanel {    

    private Supplier supplier;
    public UpdateSupplierJPanel(Supplier a) 
    {
        initComponents();      
        supplier = a;
        idField.setText(supplier.getID());
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CityTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        StateTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ZipTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        PhoneTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        WebsiteTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Update Supplier");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel2.setText("Name*:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, 20));

        NameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameTextFieldKeyTyped(evt);
            }
        });
        add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 190, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel3.setText("Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));
        add(AddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 470, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel4.setText("City:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));
        add(CityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 190, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel5.setText("State:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));
        add(StateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 40, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel9.setText("Zip Code:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));
        add(ZipTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 60, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel6.setText("Phone:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));
        add(PhoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 190, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));
        add(EmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 190, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel8.setText("Website:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));
        add(WebsiteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 190, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        idField.setBackground(new java.awt.Color(204, 204, 204));
        idField.setEditable(false);
        idField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idFieldKeyTyped(evt);
            }
        });
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 190, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel10.setText("ID:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idFieldKeyTyped
// TODO add your handling code here:
}//GEN-LAST:event_idFieldKeyTyped

    private void NameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTextFieldKeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: CANCEL  
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
   
        supplier.getPerson().setAddress(AddressTextField.getText());
        supplier.getPerson().setCity(CityTextField.getText());
        supplier.getPerson().setEmail(EmailTextField.getText());
        supplier.getPerson().setPhoneNumber(PhoneTextField.getText());
        supplier.getPerson().setState(StateTextField.getText());
        supplier.getPerson().setZip(ZipTextField.getText());
        supplier.setWebsite(WebsiteTextField.getText());
        supplier.getPerson().setFirstName(NameTextField.getText());
        supplier.getPerson().setCity(CityTextField.getText());
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);       
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextField CityTextField;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JTextField StateTextField;
    private javax.swing.JTextField WebsiteTextField;
    private javax.swing.JTextField ZipTextField;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    
}
