package UserInterface.SystemAdmin;

import Business.SystemAdmin.Person;
import UserInterface.Util.*;

public class ViewPersonDetailJPanel extends javax.swing.JPanel {
    
    private Person person;
    public ViewPersonDetailJPanel(Person p) 
    {
        initComponents();
        person = p;

        firstNameTextField.setText(person.getFirstName());
        lastNameTextField.setText(person.getLastName());       
        dobTextField.setText(person.getBirthDate());        
        addressTextField.setText(person.getAddress());
        cityTextField.setText(person.getCity());
        stateTextField.setText(person.getState());
        zipTextField.setText(person.getZip());
        phoneTextField.setText(person.getPhoneNumber());
        emailTextField.setText(person.getEmail());   
        statusTextField.setText(person.getState());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        firstNameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        dobTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stateTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        zipTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Person Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel11.setText("Address:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel3.setText("First Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel13.setText("Birth Date:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        firstNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        firstNameTextField.setEditable(false);
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 190, -1));

        addressTextField.setBackground(new java.awt.Color(204, 204, 204));
        addressTextField.setEditable(false);
        add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 190, -1));

        dobTextField.setBackground(new java.awt.Color(204, 204, 204));
        dobTextField.setEditable(false);
        add(dobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 190, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel5.setText("Last Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        lastNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        lastNameTextField.setEditable(false);
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 160, -1));

        emailTextField.setBackground(new java.awt.Color(204, 204, 204));
        emailTextField.setEditable(false);
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 190, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel8.setText("Phone:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        phoneTextField.setBackground(new java.awt.Color(204, 204, 204));
        phoneTextField.setEditable(false);
        add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 190, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel6.setText("City:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        cityTextField.setBackground(new java.awt.Color(204, 204, 204));
        cityTextField.setEditable(false);
        add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 190, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel9.setText("State:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        stateTextField.setBackground(new java.awt.Color(204, 204, 204));
        stateTextField.setEditable(false);
        add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 40, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel10.setText("Zip Code:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        zipTextField.setBackground(new java.awt.Color(204, 204, 204));
        zipTextField.setEditable(false);
        add(zipTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 80, -1));

        jButton3.setText("Disable");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel12.setText("Status:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        statusTextField.setBackground(new java.awt.Color(204, 204, 204));
        statusTextField.setEditable(false);
        add(statusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 190, -1));

    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          person.setStatus(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        
        UpdatePersonJPanel upjp = new UpdatePersonJPanel(person);
        CardLayoutUtil.getCardLayoutJPanel().addAndMoveToNextJPanel("UpdatePersonJPanel", upjp);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here: BACK
        CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
    
}
