/*
 * SalesVolumeByCustomer.java
 *
 * Created on 2008年12月20日, 下午11:31
 */

package UserInterface.ManagementReport;

import Business.Business;
import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.Customer.Order;
import Business.Customer.SolutionItem;
import Business.Market.Market;
import UserInterface.Util.CardLayoutUtil;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  kunren
 */
public class SalesVolumeByCustomer extends javax.swing.JPanel {

    /** Creates new form SalesVolumeByCustomer */
    private Business business;
    private CustomerDirectory customerdirectory;
    ArrayList <Customer>  customerlist ;
    public SalesVolumeByCustomer(Business a) {
        initComponents();
        business = a;
        customerdirectory = business.getCustomerDirectory();
        customerlist = customerdirectory.getCustomers();
        computeSalesVolume();
        Comparator comp = new Customercomparator();
        Collections.sort(customerlist,comp);
        refresh();
    }
    public void refresh()
    {
          int rowCount = customerTable.getRowCount();
        int i;
        for (i = rowCount-1; i >= 0; i--)
        {
            ((DefaultTableModel)customerTable.getModel()).removeRow(i);
        }
        
        for (Customer p : customerlist)
        {            
            Object[] user_row = new Object[4];
            
            user_row[0] = p;
            user_row[1] = p.getPerson().getPhoneNumber();     
            Market market = business.getMarketList().getMarketFromCustomer(p);
            user_row[2] = market;
            user_row[3] = p.getSalesVolume();
            
            ((DefaultTableModel)customerTable.getModel()).addRow(user_row);
        }
    }
    public void  computeSalesVolume()
    { 
        double salevolume;
       
       for(Customer customer:customerlist)
       {
           salevolume = 0;
           ArrayList <Order> orders = customer.getOrders();
           for(Order order: orders)
           {
               salevolume = salevolume + order.getTotalPrice();
           }
           ArrayList <SolutionItem> solutionItems = customer.getSolutionItems();
           for(SolutionItem a:solutionItems)
           {
               salevolume = salevolume + a.getTotalAmount();
           }
           customer.setSalesVolume(salevolume);
       }
       
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sales Volume By Customer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("sort from highest to lowest");

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer name:", "Phonenumber:", "Market:", "SalesVolume:"
            }
        ));
        jScrollPane1.setViewportView(customerTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
     CardLayoutUtil.getCardLayoutJPanel().removeAndMoveToPreviousJPanel(this);
}//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
